import { DocumentBuilder, SwaggerDocumentOptions } from '@nestjs/swagger';

/**
 * Swagger 配置接口
 */
export interface SwaggerConfig {
  /** 是否启用 Swagger，默认根据环境变量 SWAGGER_ENABLED 或开发环境自动启用 */
  enabled?: boolean;
  
  /** Swagger UI 路径，默认为 'docs' */
  path?: string;
  
  /** API 文档标题 */
  title?: string;
  
  /** API 文档描述 */
  description?: string;
  
  /** API 版本 */
  version?: string;
  
  /** API 标签配置 */
  tags?: Array<{
    name: string;
    description?: string;
  }>;
  
  /** 是否添加 Bearer Auth */
  bearerAuth?: boolean;
  
  /** Swagger UI 选项 */
  swaggerOptions?: {
    /** 是否保持认证状态 */
    persistAuthorization?: boolean;
    /** 标签排序方式 */
    tagsSorter?: 'alpha' | 'method';
    /** 操作排序方式 */
    operationsSorter?: 'alpha' | 'method';
    /** 其他自定义选项 */
    [key: string]: any;
  };
  
  /** Swagger 文档选项 */
  documentOptions?: SwaggerDocumentOptions;
}

/**
 * 默认 Swagger 配置
 */
export const DEFAULT_SWAGGER_CONFIG: SwaggerConfig = {
  enabled: process.env.NODE_ENV === 'development' || process.env.SWAGGER_ENABLED === 'true',
  path: 'docs',
  title: 'API Documentation',
  description: 'API documentation generated by @ilhamtahir/nest-core',
  version: '1.0.0',
  tags: [
    { name: '认证', description: '用户认证相关接口' },
    { name: '用户管理', description: '用户管理相关接口' },
    { name: '角色管理', description: '角色权限管理接口' },
    { name: '菜单管理', description: '菜单管理接口' },
    { name: '文件管理', description: '文件上传下载接口' },
  ],
  bearerAuth: true,
  swaggerOptions: {
    persistAuthorization: true,
    tagsSorter: 'alpha',
    operationsSorter: 'alpha',
  },
};

/**
 * 合并 Swagger 配置
 */
export function mergeSwaggerConfig(userConfig?: Partial<SwaggerConfig>): SwaggerConfig {
  if (!userConfig) {
    return DEFAULT_SWAGGER_CONFIG;
  }
  
  return {
    ...DEFAULT_SWAGGER_CONFIG,
    ...userConfig,
    tags: userConfig.tags ? [...(DEFAULT_SWAGGER_CONFIG.tags || []), ...userConfig.tags] : DEFAULT_SWAGGER_CONFIG.tags,
    swaggerOptions: {
      ...DEFAULT_SWAGGER_CONFIG.swaggerOptions,
      ...userConfig.swaggerOptions,
    },
  };
}

/**
 * 创建 Swagger DocumentBuilder
 */
export function createSwaggerDocumentBuilder(config: SwaggerConfig): DocumentBuilder {
  const builder = new DocumentBuilder()
    .setTitle(config.title!)
    .setDescription(config.description!)
    .setVersion(config.version!);
  
  // 添加标签
  if (config.tags) {
    config.tags.forEach(tag => {
      builder.addTag(tag.name, tag.description);
    });
  }
  
  // 添加 Bearer Auth
  if (config.bearerAuth) {
    builder.addBearerAuth();
  }
  
  return builder;
}
